package ai;

import java.util.ArrayList;
import java.util.List;

/**
 * ==============================================================================
 * PROJECT: Smart Waste Collection Router (Team 10)
 * SUBJECT: AI (Route Planning Solution Model)
 * ==============================================================================
 * 
 * RoutePlan stores the complete navigational trajectory generated by A*
 * along with performance metrics (distance, fuel, waste collected).
 */
public class RoutePlan {
    private List<String> nodePath; // Sequence of road graph nodes visited
    private List<String> servicedBinIds; // Which bins had waste collected
    private double totalDistanceKm;
    private double estimatedFuelLiters;
    private double totalWasteCollectedLiters;

    public RoutePlan() {
        this.nodePath = new ArrayList<>();
        this.servicedBinIds = new ArrayList<>();
        this.totalDistanceKm = 0.0;
        this.estimatedFuelLiters = 0.0;
        this.totalWasteCollectedLiters = 0.0;
    }

    public void addNodeToPath(String nodeId) {
        nodePath.add(nodeId);
    }

    public void addServicedBin(String binId) {
        servicedBinIds.add(binId);
    }

    public void addDistance(double distanceKm) {
        this.totalDistanceKm += distanceKm;
    }

    public void setEstimatedFuelLiters(double fuel) {
        this.estimatedFuelLiters = fuel;
    }

    public void setTotalWasteCollectedLiters(double waste) {
        this.totalWasteCollectedLiters = waste;
    }

    public List<String> getNodePath() { return nodePath; }
    public List<String> getServicedBinIds() { return servicedBinIds; }
    public double getTotalDistanceKm() { return totalDistanceKm; }
    public double getEstimatedFuelLiters() { return estimatedFuelLiters; }
    public double getTotalWasteCollectedLiters() { return totalWasteCollectedLiters; }

    @Override
    public String toString() {
        return String.format("Route: %s\nDistance: %.2f km | Fuel: %.2f L | Bins Serviced: %d | Total Waste: %.0f L",
                String.join(" -> ", nodePath), totalDistanceKm, estimatedFuelLiters, 
                servicedBinIds.size(), totalWasteCollectedLiters);
    }
}
